[boot]
; 3: use ramdisk loaded from kolibri.img
; 5: don't use ramdisk, use /sys directory
imgfrom=3

; Path to /sys directory, only internal
; disk drives are alowed (no usbdisk).
; Example: syspath=/HD0/1/KOLIBRIOS
syspath=

; Start LAUNCHER app after kernel is loaded
launcher_path=/sys/LAUNCHER
launcher_start=1

; Configure MTRR's
mtrr=0

skip_mouse=1
mouse_type=none

[graphic]
; Screen resolution
resolution=1024x768

; Duplicate debug output to the screen
debug_print=0